-----1. Client Billing Report----
 
 
SELECT 

    CBV.CLIENTID, 

    CBV.FIRSTNAME || ' ' || CBV.LASTNAME AS CLIENT_NAME,

    CBV.EMAIL,

    COUNT(CBV.BILLID) AS TOTAL_BILLS,

    SUM(CASE WHEN CBV.STATUS = 'Paid' THEN CBV.TOTALAMOUNT ELSE 0 END) AS TOTAL_PAID,

    SUM(CASE WHEN CBV.STATUS = 'Unpaid' THEN CBV.TOTALAMOUNT ELSE 0 END) AS TOTAL_UNPAID,

    COUNT(CASE WHEN CBV.STATUS = 'Unpaid' AND CBV.BILLPERIODEND < SYSDATE THEN 1 ELSE NULL END) AS OVERDUE_BILLS

FROM 

    Client_Bill_View CBV

GROUP BY 

    CBV.CLIENTID, CBV.FIRSTNAME, CBV.LASTNAME, CBV.EMAIL

ORDER BY 

    CBV.CLIENTID;

 
------2. Regional Client Summary-----

SELECT 

    RCC.REGION_NAME,

    RCC.CLIENT_COUNT,

    SUM(BSVR.TOTAL_BILLING_AMOUNT) AS TOTAL_BILLING_AMOUNT,

    COUNT(DISTINCT ARA.CLIENTID) AS ACTIVE_CLIENTS

FROM 

    Region_Client_Count RCC

LEFT JOIN 

    Billing_Summary_By_Region BSVR ON RCC.REGION_NAME = BSVR.REGION_NAME

LEFT JOIN 

    Active_Resource_Allocations ARA ON RCC.REGION_NAME = BSVR.REGION_NAME

GROUP BY 

    RCC.REGION_NAME, RCC.CLIENT_COUNT;

 
-------3. Resource Utilization Report------

SELECT 

    RUS.TYPENAME AS RESOURCE_TYPE,

    RUS.TOTAL_USAGE_AMOUNT,

    RUS.TOTAL_USAGE_COST,

    GRA.AVAILABLE_COUNT AS AVAILABLE_RESOURCES,

    RCC.CLIENT_COUNT AS UNIQUE_CLIENTS

FROM 

    Resource_Usage_Summary RUS

LEFT JOIN 

    Resource_Client_Count RCC ON RUS.TYPENAME = RCC.TYPENAME

LEFT JOIN 

    (SELECT RESOURCETYPEID, SUM(QUANTITYONHAND) AS AVAILABLE_COUNT 

     FROM RESOURCETABLE GROUP BY RESOURCETYPEID) GRA 

    ON RUS.RESOURCETYPEID = GRA.RESOURCETYPEID;

 
--------4. Overdue Bills Report-------

SELECT 

    OB.CLIENTID, 

    OB.CLIENT_NAME,

    COUNT(OB.BILLID) AS OVERDUE_BILLS_COUNT,

    SUM(OB.TOTALAMOUNT) AS TOTAL_OVERDUE_AMOUNT

FROM 

    Overdue_Bills OB

GROUP BY 

    OB.CLIENTID, OB.CLIENT_NAME

ORDER BY 

    TOTAL_OVERDUE_AMOUNT DESC;

 
-------5. Pricing Plan Distribution------
SELECT 

    CPP.PLANNAME AS PRICING_PLAN,

    CPP.DESCRIPTION,

    COUNT(DISTINCT CPP.CLIENTID) AS TOTAL_CLIENTS

FROM 

    Client_Pricing_Plan_View CPP

GROUP BY 

    CPP.PLANNAME, CPP.DESCRIPTION

ORDER BY 

    TOTAL_CLIENTS DESC;

 
-------6. Historical Resource Allocation Report------

SELECT 

    CRAH.CLIENTID, 

    CRAH.CLIENT_NAME,

    COUNT(CRAH.ALLOCATIONID) AS TOTAL_ALLOCATIONS,

    COUNT(CASE WHEN CRAH.STATUS = 'Approved' THEN 1 ELSE NULL END) AS APPROVED_ALLOCATIONS,

    COUNT(CASE WHEN CRAH.STATUS = 'Expired' THEN 1 ELSE NULL END) AS EXPIRED_ALLOCATIONS,

    COUNT(CASE WHEN CRAH.STATUS = 'Rejected' THEN 1 ELSE NULL END) AS REJECTED_ALLOCATIONS

FROM 

    Client_Resource_Allocation_History CRAH

GROUP BY 

    CRAH.CLIENTID, CRAH.CLIENT_NAME

ORDER BY 

    CRAH.CLIENTID;

 
------7. Active Resource Allocation Summary------

SELECT 

    ARA.CLIENTID,

    ARA.CLIENT_NAME,

    COUNT(ARA.ALLOCATIONID) AS ACTIVE_ALLOCATIONS,

    LISTAGG(ARA.RESOURCE_STATUS, ', ') WITHIN GROUP (ORDER BY ARA.RESOURCE_STATUS) AS RESOURCE_STATUSES

FROM 

    Active_Resource_Allocations ARA

GROUP BY 

    ARA.CLIENTID, ARA.CLIENT_NAME;

 
--------8. Regional Billing and Usage Summary--------

WITH Regional_Billing AS (
    SELECT 
        r.REGION_NAME, 
        SUM(b.TOTALAMOUNT) AS TOTAL_BILLING_AMOUNT
    FROM 
        REGION r
    JOIN STATE_REGION_MAPPING srm ON r.REGION_ID = srm.REGION_ID
    JOIN CLIENT c ON srm.STATE_CODE = c.STATE
    JOIN RESOURCEALLOCATION ra ON c.CLIENTID = ra.CLIENTID
    JOIN USAGELOG ul ON ra.ALLOCATIONID = ul.ALLOCATIONID
    JOIN BILL b ON ul.BILLID = b.BILLID
    GROUP BY 
        r.REGION_NAME
),
Regional_Resource_Usage AS (
    SELECT 
        r.REGION_NAME,
        rt.TYPENAME AS RESOURCE_TYPE,
        SUM(ul.USAGEAMOUNT) AS TOTAL_USAGE_AMOUNT,
        SUM(ul.TOTALCOST) AS TOTAL_USAGE_COST
    FROM 
        REGION r
    JOIN STATE_REGION_MAPPING srm ON r.REGION_ID = srm.REGION_ID
    JOIN CLIENT c ON srm.STATE_CODE = c.STATE
    JOIN RESOURCEALLOCATION ra ON c.CLIENTID = ra.CLIENTID
    JOIN RESOURCETABLE res ON ra.RESOURCEID = res.RESOURCEID
    JOIN RESOURCETYPE rt ON res.RESOURCETYPEID = rt.RESOURCETYPEID
    JOIN USAGELOG ul ON ra.ALLOCATIONID = ul.ALLOCATIONID
    GROUP BY 
        r.REGION_NAME, rt.TYPENAME
)
SELECT 
    rb.REGION_NAME,
    rb.TOTAL_BILLING_AMOUNT,
    rru.RESOURCE_TYPE,
    rru.TOTAL_USAGE_AMOUNT,
    rru.TOTAL_USAGE_COST
FROM 
    Regional_Billing rb
LEFT JOIN 
    Regional_Resource_Usage rru
ON 
    rb.REGION_NAME = rru.REGION_NAME
ORDER BY 
    rb.REGION_NAME, rru.RESOURCE_TYPE;