---- testing trigger -------
-- Set up a resource with sufficient stock
UPDATE RESOURCETABLE
SET QUANTITYONHAND = 10, THRESHOLDVALUE = 5
WHERE RESOURCEID = 1;

-- Attempt to allocate a resource
INSERT INTO RESOURCEALLOCATION (CLIENTID, RESOURCEID, REQUESTDATE, ALLOCATIONDATE, EXPIRATIONDATE, STATUS)
VALUES (1, 1, SYSDATE, SYSDATE + 1, SYSDATE + 30, NULL);

-- Verify the resource's quantity and allocation status
SELECT * FROM RESOURCETABLE WHERE RESOURCEID = 1;
SELECT * FROM RESOURCEALLOCATION WHERE RESOURCEID = 1;


-- Set resource quantity below the threshold
UPDATE RESOURCETABLE
SET QUANTITYONHAND = 3
WHERE RESOURCEID = 1;

-- Attempt to allocate a resource
INSERT INTO RESOURCEALLOCATION (CLIENTID, RESOURCEID, REQUESTDATE, ALLOCATIONDATE, EXPIRATIONDATE, STATUS)
VALUES (2, 1, SYSDATE, SYSDATE + 1, SYSDATE + 30, NULL);

-- Verify the resource's quantity and allocation status
SELECT * FROM RESOURCETABLE WHERE RESOURCEID = 1;
SELECT * FROM RESOURCEALLOCATION WHERE RESOURCEID = 1;


-- Set resource quantity to 0
UPDATE RESOURCETABLE
SET QUANTITYONHAND = 0
WHERE RESOURCEID = 1;

-- Attempt to allocate a resource
INSERT INTO RESOURCEALLOCATION (CLIENTID, RESOURCEID, REQUESTDATE, ALLOCATIONDATE, EXPIRATIONDATE, STATUS)
VALUES (3, 1, SYSDATE, SYSDATE + 1, SYSDATE + 30, NULL);

-- Verify the resource's quantity and allocation status
SELECT * FROM RESOURCETABLE WHERE RESOURCEID = 1;
SELECT * FROM RESOURCEALLOCATION WHERE RESOURCEID = 1;

--------- bill trigger

-- Insert a new usage log
INSERT INTO USAGELOG (ALLOCATIONID, STARTTIME, ENDTIME, USAGEAMOUNT, BILLID, TOTALCOST)
VALUES (1, SYSDATE - 1, SYSDATE, 10, 1, 15);

-- Verify the total amount in the BILL table
SELECT * FROM BILL WHERE BILLID = 1;

-- Update the total cost of a usage log
UPDATE USAGELOG
SET TOTALCOST = 20
WHERE LOGID=12;
INSERT INTO USAGELOG (ALLOCATIONID, STARTTIME, ENDTIME, USAGEAMOUNT, BILLID, TOTALCOST)
VALUES (1, SYSDATE - 1, SYSDATE, 10, 1, 15);

-- Verify the total amount in the BILL table
SELECT * FROM BILL WHERE BILLID = 1;

 
 
 ---- Testing Threshold_Alert Trigger

-- Update resource quantity above threshold
UPDATE RESOURCETABLE
SET QUANTITYONHAND = 10
WHERE RESOURCEID = 2;

-- Update resource quantity below threshold
UPDATE RESOURCETABLE
SET QUANTITYONHAND = 3
WHERE RESOURCEID = 2;

-- Check DBMS output for the alert
